"""Aggregate cosmic-ray mutation-testing sessions into one baseline report.

Issue #5: selective mutation-testing baseline for critical, deterministic
domain modules. Each module has its own cosmic-ray session (config +
sqlite db) under mutation/, since cosmic-ray's module-path takes one file
or package and our four candidates are scattered across the tree. This
script reads all four sessions and writes one combined
docs/quality/mutation.json (every mutant) and docs/quality/mutation.md
(per-module score + every surviving mutant, for review).

Usage (after running each session, see mutation/README.md):
    python scripts/mutation_report.py
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parent.parent
SESSIONS = [
    "correction_model",
    "collimation_measurement",
    "collimation_state",
    "roi_tracker",
]
OUT_DIR = REPO_ROOT / "docs" / "quality"


def _dump_session(name: str) -> list[dict[str, Any]]:
    db = REPO_ROOT / "mutation" / f"{name}.sqlite"
    proc = subprocess.run(
        [sys.executable, "-m", "cosmic_ray.cli", "dump", str(db)],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=True,
    )
    items = []
    for line in proc.stdout.splitlines():
        if not line.strip():
            continue
        work_item, result = json.loads(line)
        items.append({"work_item": work_item, "result": result})
    return items


def _summarize(name: str, items: list[dict[str, Any]]) -> dict[str, Any]:
    total = len(items)
    outcomes: dict[str, int] = {}
    survivors = []
    for item in items:
        outcome = item["result"]["test_outcome"]
        outcomes[outcome] = outcomes.get(outcome, 0) + 1
        if outcome == "survived":
            mutation = item["work_item"]["mutations"][0]
            survivors.append(
                {
                    "operator": mutation["operator_name"],
                    "line": mutation["start_pos"][0],
                    "function": mutation.get("definition_name"),
                    "diff": item["result"]["diff"],
                }
            )
    killed = outcomes.get("killed", 0)
    survived = outcomes.get("survived", 0)
    # Score over killed+survived only — incompetent mutants (e.g. a
    # decorator removal that breaks collection) aren't a meaningful pass/
    # fail signal either way, so they're excluded from the denominator.
    scored = killed + survived
    score = round(100 * killed / scored, 1) if scored else None
    return {
        "module": name,
        "total_mutants": total,
        "outcomes": outcomes,
        "mutation_score_percent": score,
        "surviving_mutants": survivors,
    }


def _render_markdown(summaries: list[dict[str, Any]]) -> str:
    lines = [
        "# Mutation-testing baseline",
        "",
        "Generated by `scripts/mutation_report.py` (issue #5), via cosmic-ray "
        "against each module's own dedicated test file. Selective scope per the "
        "issue: pure/near-pure deterministic domain modules only, not UI/"
        "threading/hardware adapters. Score = killed / (killed + survived); "
        "incompetent mutants (test collection broke, e.g. a decorator removal) "
        "are excluded from the denominator as a non-signal, not counted as a "
        "pass.",
        "",
        "| Module | Mutants | Killed | Survived | Incompetent | Score |",
        "|---|---|---|---|---|---|",
    ]
    for s in summaries:
        o = s["outcomes"]
        lines.append(
            f"| `{s['module']}` | {s['total_mutants']} | {o.get('killed', 0)} | "
            f"{o.get('survived', 0)} | {o.get('incompetent', 0)} | "
            f"{s['mutation_score_percent']}% |"
        )
    lines.append("")
    lines.append(
        "No threshold is enforced yet (see issue #9, blocked on this baseline "
        "plus issue #4's CRAP baseline). Hardening tests for the surviving "
        "mutants below is issue #8's scope, not this one."
    )
    lines.append("")

    for s in summaries:
        if not s["surviving_mutants"]:
            continue
        lines.append(f"## Surviving mutants — `{s['module']}`")
        lines.append("")
        for m in s["surviving_mutants"]:
            lines.append(f"- `{m['operator']}` in `{m['function']}` (line {m['line']})")
        lines.append("")

    return "\n".join(lines)


def main() -> None:
    summaries = []
    all_items: dict[str, list[dict[str, Any]]] = {}
    for name in SESSIONS:
        items = _dump_session(name)
        all_items[name] = items
        summaries.append(_summarize(name, items))

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    (OUT_DIR / "mutation.json").write_text(
        json.dumps(summaries, indent=2) + "\n", encoding="utf-8"
    )
    markdown = _render_markdown(summaries)
    (OUT_DIR / "mutation.md").write_text(markdown, encoding="utf-8")
    print(markdown)


if __name__ == "__main__":
    main()
