"""Combine per-function cyclomatic complexity (radon) and statement coverage
(coverage.py, via the .coverage data pytest-cov already writes) into a CRAP
score, and report the current risk baseline.

Measurement-first per issue #4: this script never changes production code or
enforces a threshold — it only reports. Downstream refactoring/test-hardening
belongs to separate issues (#7, #8) once this baseline shows a hotspot is
materially risky.

Usage:
    pytest                       # writes .coverage (any normal run does this)
    python scripts/quality_report.py

Writes docs/quality/hotspots.json (every function) and docs/quality/hotspots.md
(top 10, human-readable) and prints the same top-10 table to stdout.

CRAP formula (Alberto Savoia / Bob Evans): complexity^2 * (1 - coverage)^3 +
complexity. Low complexity or high coverage alone keeps CRAP low; only their
combination — hard-to-reason-about code that tests don't protect — scores
high.
"""

from __future__ import annotations

import json
import subprocess
import sys
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any

import coverage

REPO_ROOT = Path(__file__).resolve().parent.parent
SOURCE_ROOTS = [
    "packages/astrotool_core",
    "apps/collimation_tool",
    "apps/guide_tool",
]
OUT_DIR = REPO_ROOT / "docs" / "quality"
TOP_N = 10


@dataclass
class Hotspot:
    file: str
    function: str
    complexity: int
    coverage_percent: float
    crap: float


def _run_radon() -> dict[str, list[dict[str, Any]]]:
    proc = subprocess.run(
        [sys.executable, "-m", "radon", "cc", "-j", *SOURCE_ROOTS],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=True,
    )
    result: dict[str, list[dict[str, Any]]] = json.loads(proc.stdout)
    return result


def _load_coverage_functions() -> dict[str, dict[str, dict[str, Any]]]:
    """Return {file: {function_key: summary_dict}} from the .coverage data
    pytest-cov already wrote (run `pytest` first if this raises)."""
    data_file = REPO_ROOT / ".coverage"
    if not data_file.exists():
        raise SystemExit(
            "No .coverage file found — run `pytest` (or scripts/check.ps1) first "
            "so there is coverage data to combine with complexity."
        )
    cov = coverage.Coverage(data_file=str(data_file))
    cov.load()
    tmp_json = REPO_ROOT / ".quality_report_coverage.json"
    cov.json_report(outfile=str(tmp_json))
    report = json.loads(tmp_json.read_text(encoding="utf-8"))
    tmp_json.unlink()
    return {
        file: {name: entry["summary"] for name, entry in data["functions"].items()}
        for file, data in report["files"].items()
    }


def _function_entries(radon_file_entries: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """radon's per-file list repeats methods both flattened and nested under
    their class entry — keep only the flattened function/method entries."""
    return [entry for entry in radon_file_entries if entry["type"] in ("function", "method")]


def build_hotspots() -> list[Hotspot]:
    radon_data = _run_radon()
    coverage_data = _load_coverage_functions()

    hotspots: list[Hotspot] = []
    for file, entries in radon_data.items():
        file_coverage = coverage_data.get(file, {})
        for entry in _function_entries(entries):
            classname = entry.get("classname")
            key = f"{classname}.{entry['name']}" if classname else entry["name"]
            summary = file_coverage.get(key)
            # No measured statements (e.g. a trivial stub) -> nothing to miss.
            coverage_percent = summary["percent_covered"] if summary is not None else 100.0
            complexity = entry["complexity"]
            coverage_fraction = coverage_percent / 100.0
            crap = complexity**2 * (1 - coverage_fraction) ** 3 + complexity
            hotspots.append(
                Hotspot(
                    file=file.replace("\\", "/"),
                    function=key,
                    complexity=complexity,
                    coverage_percent=round(coverage_percent, 1),
                    crap=round(crap, 2),
                )
            )

    hotspots.sort(key=lambda h: h.crap, reverse=True)
    return hotspots


def _render_markdown(hotspots: list[Hotspot]) -> str:
    lines = [
        "# Complexity/coverage hotspot baseline",
        "",
        "Generated by `scripts/quality_report.py` (issue #4). CRAP = "
        "complexity^2 * (1 - coverage)^3 + complexity — informational only, "
        "no threshold is enforced yet (see issue #9).",
        "",
        "**Complexity here is radon's, not ruff's.** The two tools count McCabe "
        "branches differently and can disagree substantially on the same "
        "function (e.g. `CollimationRecenterPolicy.center`: ruff C901 reports "
        "10, radon reports 19). Ruff's `C90` gate (max 15, see pyproject.toml) "
        "remains the enforced threshold; this report's numbers and ranking are "
        "context for reviewing a hotspot, not a competing gate.",
        "",
        "| Rank | CRAP | Complexity | Coverage | Function | File |",
        "|---|---|---|---|---|---|",
    ]
    for i, h in enumerate(hotspots[:TOP_N], start=1):
        lines.append(
            f"| {i} | {h.crap} | {h.complexity} | {h.coverage_percent}% | "
            f"`{h.function}` | `{h.file}` |"
        )
    lines.append("")
    lines.append(f"Full data for all {len(hotspots)} functions: `docs/quality/hotspots.json`.")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    hotspots = build_hotspots()
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    (OUT_DIR / "hotspots.json").write_text(
        json.dumps([asdict(h) for h in hotspots], indent=2) + "\n", encoding="utf-8"
    )
    markdown = _render_markdown(hotspots)
    (OUT_DIR / "hotspots.md").write_text(markdown, encoding="utf-8")
    print(markdown)


if __name__ == "__main__":
    main()
